# Generated by Django 4.0.2 on 2022-04-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=30, verbose_name='Тегі')),
                ('phone_number', models.IntegerField(verbose_name='Нөмірі')),
                ('data', models.DateField(verbose_name='Туған жылы')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('password', models.CharField(max_length=8, verbose_name='Құпия сөз')),
                ('password1', models.CharField(max_length=8, verbose_name='Құпия сөзді қайталыныз')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
