# Generated by Django 4.0.2 on 2022-04-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_us_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Us',
            new_name='User',
        ),
    ]
