# Generated by Django 4.0.2 on 2022-04-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_us_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
