# Generated by Django 4.0.2 on 2022-04-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_name',
            new_name='firs',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='number',
        ),
    ]
