# Generated by Django 4.0.2 on 2022-04-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
    ]
