# Generated by Django 4.0.2 on 2022-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.UUIDField(editable=False),
        ),
    ]
