# Generated by Django 4.0.2 on 2022-04-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
